// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hello struct {
	ID   int    `json:"ID"`
	Name string `json:"name"`
}

type NewHello struct {
	Name string `json:"name"`
}
